-- MySQL Script generated by MySQL Workbench
-- Fri Sep 11 20:10:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema A1BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema A1BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `A1BD` DEFAULT CHARACTER SET utf8 ;
USE `A1BD` ;

-- -----------------------------------------------------
-- Table `A1BD`.`Macro nutrientes - Principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro nutrientes - Principal` (
  `id_macro` INT NOT NULL,
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  PRIMARY KEY (`id_macro`),
  UNIQUE INDEX `id_macro_UNIQUE` (`id_macro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Verduras, hortaliças e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Verduras, hortaliças e derivados` (
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Verduras, hortaliças e derivados_Macro nutrientes1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Alimentos preparados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Alimentos preparados` (
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Alimentos preparados_Macro nutrientes - Principal1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Gorduras e óleos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Gorduras e óleos` (
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Gorduras e óleos_Macro nutrientes - Principal1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Frutas e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Frutas e derivados` (
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Frutas e derivados_Macro nutrientes - Principal1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Produtos açucarados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Produtos açucarados` (
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  UNIQUE INDEX `Macro nutrientes - Principal_id_macro_UNIQUE` (`Macro nutrientes - Principal_id_macro` ASC) VISIBLE,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Produtos açucarados_Macro nutrientes - Principal1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Outros alimentos industrializados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Outros alimentos industrializados` (
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Outros alimentos industrializados_Macro nutrientes1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Miscelâneas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Miscelâneas` (
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Miscelâneas_Macro nutrientes - Principal1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Ovos e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Ovos e derivados` (
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Ovos e derivados_Macro nutrientes - Principal1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Bebidas (alcoólicas e não alcoólicas)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Bebidas (alcoólicas e não alcoólicas)` (
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Bebidas (alcoólicas e não alcoólicas)_Macro nut1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Leite e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Leite e derivados` (
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Leite e derivados_Macro nutrientes - Principal1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Carnes e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Carnes e derivados` (
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Carnes e derivados_Macro nutrientes - Principal1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Pescados e frutos do mar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Pescados e frutos do mar` (
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Pescados e frutos do mar_Macro nutrientes - Princi1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Leguminosas e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Leguminosas e derivados` (
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Leguminosas e derivados_Macro nutrientes - Princip1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Nozes e sementes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Nozes e sementes` (
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Nozes e sementes_Macro nutrientes - Principal1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Macro - Cereais e Derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Macro - Cereais e Derivados` (
  `Macro nutrientes - Principal_id_macro` INT NOT NULL,
  `descricao` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `umidade` DECIMAL(3,1) NULL,
  `energia(kcal)` INT NULL,
  `energia(KJ)` INT NULL,
  `proteina(g)` DECIMAL(2,1) NULL,
  `lipidios(g)` DECIMAL(2,1) NULL,
  `colesterol(mg)` DECIMAL(3,1) NULL,
  `carboidratos(g)` DECIMAL(3,1) NULL,
  `fibra_alimentar(g)` DECIMAL(2,1) NULL,
  `cinzas(g)` DECIMAL(2,1) NULL,
  `calcio(mg)` INT NULL,
  `magnesio(mg)` INT NULL,
  PRIMARY KEY (`Macro nutrientes - Principal_id_macro`),
  CONSTRAINT `fk_Macro - Cereais e Derivados_Macro nutrientes - Principal1`
    FOREIGN KEY (`Macro nutrientes - Principal_id_macro`)
    REFERENCES `A1BD`.`Macro nutrientes - Principal` (`id_macro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro nutrientes - Principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro nutrientes - Principal` (
  `id_micro` INT NOT NULL,
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  PRIMARY KEY (`id_micro`),
  UNIQUE INDEX `id_micro_UNIQUE` (`id_micro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Cereais e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Cereais e derivados` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Cereais e derivados_Micro nutrientes - Principal1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Verduras,hortaliças e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Verduras,hortaliças e derivados` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Verduras,hortaliças e derivados_Micro nutrientes 1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Ovos e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Ovos e derivados` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Ovos e derivados_Micro nutrientes - Principal1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Produtos açucarados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Produtos açucarados` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Produtos açucarados_Micro nutrientes - Principal1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Miscelâneas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Miscelâneas` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Miscelâneas_Micro nutrientes - Principal1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Outros alimentos industrializados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Outros alimentos industrializados` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Outros alimentos industrializados_Micro nutrientes1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Alimentos preparados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Alimentos preparados` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Alimentos preparados_Micro nutrientes - Principal1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Leguminosas e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Leguminosas e derivados` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Leguminosas e derivados_Micro nutrientes - Princip1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Nozes e sementes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Nozes e sementes` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Nozes e sementes_Micro nutrientes - Principal1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Frutas e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Frutas e derivados` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Frutas e derivados_Micro nutrientes - Principal1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Gorduras e óleos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Gorduras e óleos` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Gorduras e óleos_Micro nutrientes - Principal1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Pescados e frutos do mar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Pescados e frutos do mar` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Pescados e frutos do mar_Micro nutrientes - Princi1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Carnes e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Carnes e derivados` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Carnes e derivados_Micro nutrientes - Principal1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Leite e derivados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Leite e derivados` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Leite e derivados_Micro nutrientes - Principal1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A1BD`.`Micro - Bebidas (alcoólicas e não alcoólicas)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A1BD`.`Micro - Bebidas (alcoólicas e não alcoólicas)` (
  `manganês(mg)` DECIMAL(3,2) NULL,
  `fósforo(mg)` INT NULL,
  `ferro(mg)` DECIMAL(2,1) NULL,
  `sodio(mg)` INT NULL,
  `potassio(mg)` INT NULL,
  `cobre(mg)` DECIMAL(3,2) NULL,
  `zinco(mg)` DECIMAL(2,1) NULL,
  `retinol(mcg)` INT NULL,
  `re(mcg)` INT NULL,
  `rae(mcg)` INT NULL,
  `tiamina(mg)` DECIMAL(3,2) NULL,
  `riboflavina(mg)` DECIMAL(3,2) NULL,
  `piridoxina(mg)` DECIMAL(3,2) NULL,
  `niacina(mg)` DECIMAL(3,2) NULL,
  `vitamina(mg)` DECIMAL(2,1) NULL,
  `Micro nutrientes - Principal_id_micro` INT NOT NULL,
  PRIMARY KEY (`Micro nutrientes - Principal_id_micro`),
  CONSTRAINT `fk_Micro - Bebidas (alcoólicas e não alcoólicas)_Micro nut1`
    FOREIGN KEY (`Micro nutrientes - Principal_id_micro`)
    REFERENCES `A1BD`.`Micro nutrientes - Principal` (`id_micro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
