-- MySQL Script generated by MySQL Workbench
-- Sun Jul  5 20:58:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema loja_Ka7
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja_Ka7
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja_Ka7` ;
USE `loja_Ka7` ;

-- -----------------------------------------------------
-- Table `loja_Ka7`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_Ka7`.`cliente` (
  `idcliente` SMALLINT(5) UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `telefone` INT(10) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `num_residencia` VARCHAR(10) NOT NULL,
  `cep` INT(8) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC) VISIBLE,
  UNIQUE INDEX `cep_UNIQUE` (`cep` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `loja_Ka7`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_Ka7`.`funcionario` (
  `idfuncionario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cargo` VARCHAR(255) NOT NULL,
  `salario` INT(10) NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `idfuncionarios_UNIQUE` (`idfuncionario` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `loja_Ka7`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_Ka7`.`produto` (
  `idproduto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_produto` VARCHAR(7) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `ano` YEAR NOT NULL,
  `banda` VARCHAR(45) NOT NULL,
  `produtora` VARCHAR(45) NOT NULL,
  `custo` INT(5) NOT NULL,
  `estoque` VARCHAR(45) NOT NULL,
  `duracao` TIME NOT NULL,
  `album` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `idproduto_UNIQUE` (`idproduto` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `loja_Ka7`.`entregador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_Ka7`.`entregador` (
  `identregador` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `velocidade_do_cavalo_(km/h)` INT(4) NOT NULL,
  `raca` VARCHAR(45) NOT NULL,
  `nascimento_do_cavalo` DATE NOT NULL,
  PRIMARY KEY (`identregador`),
  UNIQUE INDEX `identregador_UNIQUE` (`identregador` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `loja_Ka7`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_Ka7`.`banco` (
  `idbanco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbanco`),
  UNIQUE INDEX `idbanco_UNIQUE` (`idbanco` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `loja_Ka7`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_Ka7`.`venda` (
  `idvenda` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `valor` INT(10) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL,
  `funcionario_idfuncionario` INT UNSIGNED NOT NULL,
  `produto_idproduto` INT UNSIGNED NOT NULL,
  `entregador_identregador` INT UNSIGNED NOT NULL,
  `cliente_idcliente` SMALLINT(5) UNSIGNED NOT NULL,
  `banco_idbanco` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idvenda`),
  UNIQUE INDEX `idvenda_UNIQUE` (`idvenda` ASC) VISIBLE,
  INDEX `fk_venda_funcionario1_idx` (`funcionario_idfuncionario` ASC) VISIBLE,
  INDEX `fk_venda_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  INDEX `fk_venda_entregador1_idx` (`entregador_identregador` ASC) VISIBLE,
  INDEX `fk_venda_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_venda_banco1_idx` (`banco_idbanco` ASC) VISIBLE,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `loja_Ka7`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `loja_Ka7`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_entregador1`
    FOREIGN KEY (`entregador_identregador`)
    REFERENCES `loja_Ka7`.`entregador` (`identregador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `loja_Ka7`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_banco1`
    FOREIGN KEY (`banco_idbanco`)
    REFERENCES `loja_Ka7`.`banco` (`idbanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `loja_Ka7`.`login_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_Ka7`.`login_cliente` (
  `username` VARCHAR(16) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `cliente_idcliente` SMALLINT(5) UNSIGNED NOT NULL,
  INDEX `fk_login_cliente_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_login_cliente_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `loja_Ka7`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
