-- MySQL Script generated by MySQL Workbench
-- Thu Sep  2 06:30:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Restaurante Funcional
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Restaurante Funcional
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restaurante Funcional` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema loja_Ka7
-- -----------------------------------------------------
USE `Restaurante Funcional` ;

-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`Prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`Prato` (
  `idPrato` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome_Prato` VARCHAR(255) NOT NULL,
  `Preco_Prato` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`idPrato`),
  UNIQUE INDEX `idPrato_UNIQUE` (`idPrato` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`Fornecedor` (
  `idFornecedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome_Fornecedor` VARCHAR(255) NOT NULL,
  `CNPJ_Fornecedor` INT(14) NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `idFornecedor_UNIQUE` (`idFornecedor` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_Fornecedor_UNIQUE` (`CNPJ_Fornecedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`Cliente` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome_Cliente` VARCHAR(255) NOT NULL,
  `TipoSanguineo_Cliente` VARCHAR(3) NOT NULL,
  `DataDaUltimaVisita_Cliente` DATE NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`Funcionarios` (
  `idFuncionarios` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome_Funcionarios` VARCHAR(255) NOT NULL,
  `Cargo_Funcionarios` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idFuncionarios`),
  UNIQUE INDEX `idFuncionarios_UNIQUE` (`idFuncionarios` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`Ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`Ingredientes` (
  `idIngredientes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome_Ingredientes` VARCHAR(255) NOT NULL,
  `Preco_Ingredientes` DECIMAL(9,2) NOT NULL,
  `Fornecedor_IdFornecedor` INT UNSIGNED NOT NULL,
  `Prato_IdPrato` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idIngredientes`),
  UNIQUE INDEX `idIngredientes_UNIQUE` (`idIngredientes` ASC) INVISIBLE,
  INDEX `fk_Ingredientes_Fornecedor_idx` (`Fornecedor_IdFornecedor` ASC) VISIBLE,
  INDEX `fk_Ingredientes_Prato_idx` (`Prato_IdPrato` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredientes_Fornecedor`
    FOREIGN KEY (`Fornecedor_IdFornecedor`)
    REFERENCES `Restaurante Funcional`.`Fornecedor` (`idFornecedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ingredientes_Prato`
    FOREIGN KEY (`Prato_IdPrato`)
    REFERENCES `Restaurante Funcional`.`Prato` (`idPrato`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`PagamentoDoSalario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`PagamentoDoSalario` (
  `idPagamentoDoSalario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Valor_PagamentoDoSalario` DECIMAL(9,2) NOT NULL,
  `Funcionarios_idFuncionarios` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPagamentoDoSalario`),
  UNIQUE INDEX `idPagamentoDoSalario_UNIQUE` (`idPagamentoDoSalario` ASC) VISIBLE,
  INDEX `fk_Funcionarios_PagamentoDoSalario_idx` (`Funcionarios_idFuncionarios` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionarios_PagamentoDoSalario`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `Restaurante Funcional`.`Funcionarios` (`idFuncionarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`FluxoDeCaixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`FluxoDeCaixa` (
  `idFluxoDeCaixa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Data_FluxoDeCaixa` DATE NOT NULL,
  `id_Loja` INT UNSIGNED NOT NULL,
  `id_Cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idFluxoDeCaixa`),
  UNIQUE INDEX `idFluxoDeCaixa_UNIQUE` (`idFluxoDeCaixa` ASC) VISIBLE,
  INDEX `fk_FluxoDeCaixa_PagamentoDoSalario_idx` (`id_Loja` ASC) VISIBLE,
  INDEX `fk_FluxoDeCaixa_Cliente_idx` (`id_Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_FluxoDeCaixa_PagamentoDoSalario`
    FOREIGN KEY (`id_Loja`)
    REFERENCES `Restaurante Funcional`.`PagamentoDoSalario` (`idPagamentoDoSalario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FluxoDeCaixa_Cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `Restaurante Funcional`.`Cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`IncluidoEm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`IncluidoEm` (
  `Ingredientes_idIngredientes` INT UNSIGNED NOT NULL,
  `FluxoDeCaixa_idFluxoDeCaixa` INT UNSIGNED NOT NULL,
  `Quantidade_IncluidoEm` INT(11) NOT NULL,
  INDEX `fk_IncluidoEm_Ingredientes_idx` (`Ingredientes_idIngredientes` ASC) VISIBLE,
  INDEX `fk_IncluidoEm_FluxoDeCaixa_idx` (`FluxoDeCaixa_idFluxoDeCaixa` ASC) VISIBLE,
  CONSTRAINT `fk_IncluidoEm_Ingredientes`
    FOREIGN KEY (`Ingredientes_idIngredientes`)
    REFERENCES `Restaurante Funcional`.`Ingredientes` (`idIngredientes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_IncluidoEm_FluxoDeCaixa`
    FOREIGN KEY (`FluxoDeCaixa_idFluxoDeCaixa`)
    REFERENCES `Restaurante Funcional`.`FluxoDeCaixa` (`idFluxoDeCaixa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
