-- MySQL Script generated by MySQL Workbench
-- Fri Sep  3 00:27:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Restaurante Funcional
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Restaurante Funcional
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restaurante Funcional` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema loja_Ka7
-- -----------------------------------------------------
USE `Restaurante Funcional` ;

-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `Nome_categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `idcategoria_UNIQUE` (`idcategoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`subcategoria` (
  `idsubcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome_subcategoria` VARCHAR(255) NOT NULL,
  `cod_categoria` INT NOT NULL,
  PRIMARY KEY (`idsubcategoria`),
  UNIQUE INDEX `idsubcategoria_UNIQUE` (`idsubcategoria` ASC) VISIBLE,
  INDEX `fk_subcategoria_categoria_idx` (`cod_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_subcategoria_categoria`
    FOREIGN KEY (`cod_categoria`)
    REFERENCES `Restaurante Funcional`.`categoria` (`idcategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`undmedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`undmedida` (
  `idundmedida` INT NOT NULL,
  `nome_undmedida` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idundmedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(255) NOT NULL,
  `descricao_produto` VARCHAR(255) NOT NULL,
  `quantidade_produto` INT(11) NOT NULL,
  `cals_produto` INT(11) NOT NULL,
  `gord_produto` DECIMAL(9,2) NOT NULL,
  `carbs_produto` DECIMAL(9,2) NOT NULL,
  `prot_produto` DECIMAL(9,2) NOT NULL,
  `valor_de_venda_produto` DECIMAL(9,2) NOT NULL,
  `custo_producao_produto` DECIMAL(9,2) NOT NULL,
  `cod_undmedida_produto` INT NOT NULL,
  `cod_categoria_produto` INT NOT NULL,
  `cod_subcategoria_produto` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `idPrato_UNIQUE` (`idproduto` ASC) VISIBLE,
  INDEX `fk_produto_subcategoria_idx` (`cod_subcategoria_produto` ASC) VISIBLE,
  INDEX `fk_produto_categoria_idx` (`cod_categoria_produto` ASC) VISIBLE,
  INDEX `fk_produto_undmedida_idx` (`cod_undmedida_produto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_subcategoria`
    FOREIGN KEY (`cod_subcategoria_produto`)
    REFERENCES `Restaurante Funcional`.`subcategoria` (`idsubcategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`cod_categoria_produto`)
    REFERENCES `Restaurante Funcional`.`categoria` (`idcategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produto_undmedida`
    FOREIGN KEY (`cod_undmedida_produto`)
    REFERENCES `Restaurante Funcional`.`undmedida` (`idundmedida`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`prestador` (
  `documento_prestador` VARCHAR(18) NOT NULL,
  `nome_prestador` VARCHAR(255) NOT NULL,
  `tipo_do_prestador` VARCHAR(255) NOT NULL,
  `telefone_prestador` INT(13) NULL,
  `email_prestador` VARCHAR(255) NULL,
  PRIMARY KEY (`documento_prestador`),
  UNIQUE INDEX `CNPJ_Fornecedor_UNIQUE` (`documento_prestador` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`exame` (
  `idexame` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `documento_cliente` VARCHAR(18) NOT NULL,
  `tipo_sanguineo_exame` VARCHAR(2) NOT NULL,
  `soro_rh_exame` VARCHAR(1) NOT NULL,
  `documento_coletor_exame` VARCHAR(18) NOT NULL,
  `documento_examinadador_exame` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`idexame`),
  UNIQUE INDEX `idexame_UNIQUE` (`idexame` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`loja` (
  `idloja` INT NOT NULL AUTO_INCREMENT,
  `logradouro_loja` VARCHAR(255) NOT NULL,
  `numero_loja` VARCHAR(15) NOT NULL,
  `bairro_loja` VARCHAR(255) NOT NULL,
  `uf_loja` VARCHAR(255) NOT NULL,
  `telefone_loja` INT(13) NOT NULL,
  PRIMARY KEY (`idloja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`cliente` (
  `documento_cliente` VARCHAR(18) NOT NULL,
  `nome_cliente` VARCHAR(255) NOT NULL,
  `telefone_cliente` INT(13) NOT NULL,
  PRIMARY KEY (`documento_cliente`),
  UNIQUE INDEX `documento_cliente_UNIQUE` (`documento_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_exame`
    FOREIGN KEY ()
    REFERENCES `Restaurante Funcional`.`exame` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`tipopagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`tipopagamento` (
  `idtipopagamento` INT NOT NULL AUTO_INCREMENT,
  `nome_tipopagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipopagamento`),
  UNIQUE INDEX `idtipopagamento_UNIQUE` (`idtipopagamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `data_venda` DATE NOT NULL,
  `notafiscal_venda` INT(9) NOT NULL,
  `total_venda` DECIMAL(9,2) NOT NULL,
  `desconto_venda` DECIMAL(9,2) NOT NULL DEFAULT 0.00,
  `aumento_venda` DECIMAL(9,2) NOT NULL,
  `status_venda` VARCHAR(1) NOT NULL,
  `documento_cliente` VARCHAR(18) NOT NULL,
  `cod_tipopagamento` INT NOT NULL,
  `idloja` INT NOT NULL,
  PRIMARY KEY (`idvenda`),
  UNIQUE INDEX `idvenda_UNIQUE` (`idvenda` ASC) VISIBLE,
  INDEX `fk_venda_cliente_idx` (`documento_cliente` ASC) VISIBLE,
  INDEX `fk_venda_tipopagamento_idx` (`cod_tipopagamento` ASC) VISIBLE,
  INDEX `fk_venda_loja_idx` (`idloja` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente`
    FOREIGN KEY (`documento_cliente`)
    REFERENCES `Restaurante Funcional`.`cliente` (`documento_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_venda_tipopagamento`
    FOREIGN KEY (`cod_tipopagamento`)
    REFERENCES `Restaurante Funcional`.`tipopagamento` (`idtipopagamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_venda_loja`
    FOREIGN KEY (`idloja`)
    REFERENCES `Restaurante Funcional`.`loja` (`idloja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `data_compra` DATE NOT NULL,
  `total_compra` DECIMAL(9,2) NOT NULL,
  `parcelas_compra` INT(11) NOT NULL DEFAULT 1,
  `status_compra` VARCHAR(1) NOT NULL,
  `documento_prestador` VARCHAR(18) NOT NULL,
  `cod_tipopagamento` INT NOT NULL,
  `idloja` INT NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_compra_prestador_idx` (`documento_prestador` ASC) VISIBLE,
  INDEX `fk_compra_tipopagamento_idx` (`cod_tipopagamento` ASC) VISIBLE,
  INDEX `fk_compra_loja_idx` (`idloja` ASC) VISIBLE,
  CONSTRAINT `fk_compra_prestador`
    FOREIGN KEY (`documento_prestador`)
    REFERENCES `Restaurante Funcional`.`prestador` (`documento_prestador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_compra_tipopagamento`
    FOREIGN KEY (`cod_tipopagamento`)
    REFERENCES `Restaurante Funcional`.`tipopagamento` (`idtipopagamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_compra_loja`
    FOREIGN KEY (`idloja`)
    REFERENCES `Restaurante Funcional`.`loja` (`idloja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`parcelascompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`parcelascompra` (
  `idparcelascompra` INT NOT NULL AUTO_INCREMENT,
  `valor_parcelascompra` DECIMAL(9,2) NOT NULL,
  `data_pagamento_parcelascompra` DATE NOT NULL,
  `data_vencimento_parcelascompra` DATE NOT NULL,
  `cod_compra` INT NOT NULL,
  PRIMARY KEY (`idparcelascompra`),
  UNIQUE INDEX `idparcelascompra_UNIQUE` (`idparcelascompra` ASC) VISIBLE,
  INDEX `fk_parcelascompra_compra_idx` (`cod_compra` ASC) VISIBLE,
  CONSTRAINT `fk_parcelascompra_compra`
    FOREIGN KEY (`cod_compra`)
    REFERENCES `Restaurante Funcional`.`compra` (`idcompra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`itenscompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`itenscompra` (
  `iditenscompra` INT NOT NULL AUTO_INCREMENT,
  `quantidade_itenscompra` INT(11) NOT NULL,
  `valor_itenscompra` DECIMAL(9,2) NOT NULL,
  `cod_compra` INT NOT NULL,
  `cod_produto` INT NOT NULL,
  PRIMARY KEY (`iditenscompra`),
  UNIQUE INDEX `iditenscompra_UNIQUE` (`iditenscompra` ASC) VISIBLE,
  INDEX `fk_itenscompra_compra_idx` (`cod_compra` ASC) VISIBLE,
  INDEX `fk_itenscompra_produto_idx` (`cod_produto` ASC) VISIBLE,
  CONSTRAINT `fk_itenscompra_compra`
    FOREIGN KEY (`cod_compra`)
    REFERENCES `Restaurante Funcional`.`compra` (`idcompra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_itenscompra_produto`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `Restaurante Funcional`.`produto` (`idproduto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`itensvenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`itensvenda` (
  `iditensvenda` INT NOT NULL AUTO_INCREMENT,
  `quantidade_itensvenda` INT(11) NOT NULL,
  `valor_itensvenda` DECIMAL(9,2) NOT NULL,
  `cod_venda` INT NOT NULL,
  `cod_produto` INT NOT NULL,
  PRIMARY KEY (`iditensvenda`),
  UNIQUE INDEX `iditensvenda_UNIQUE` (`iditensvenda` ASC) VISIBLE,
  INDEX `fk_itensvenda_produto_idx` (`cod_produto` ASC) VISIBLE,
  CONSTRAINT `fk_itensvenda_venda`
    FOREIGN KEY ()
    REFERENCES `Restaurante Funcional`.`venda` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itensvenda_produto`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `Restaurante Funcional`.`produto` (`idproduto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante Funcional`.`parcelasvenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante Funcional`.`parcelasvenda` (
  `idparcelasvenda` INT NOT NULL AUTO_INCREMENT,
  `cod_venda` INT NOT NULL,
  `valor_parcelasvenda` DECIMAL(9,2) NOT NULL,
  `data_pagamento_parcelasvenda` DATE NOT NULL,
  `data_vencimento_parcelasvenda` DATE NOT NULL,
  PRIMARY KEY (`idparcelasvenda`),
  UNIQUE INDEX `idparcelasvenda_UNIQUE` (`idparcelasvenda` ASC) VISIBLE,
  INDEX `fk_parcelasvenda_venda_idx` (`cod_venda` ASC) VISIBLE,
  CONSTRAINT `fk_parcelasvenda_venda`
    FOREIGN KEY (`cod_venda`)
    REFERENCES `Restaurante Funcional`.`venda` (`idvenda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
